### ISSUE TITLE
skylark.Call: panics with nil function

### ISSUE THREAD

**Issue by natefinch** [google/skylark#10]
I hit this when I was wrestling with #9.

If skylark.Call is passed a nil function, it will panic here: https://github.com/google/skylark/blob/13998aa7464402849172959d67ded8527c7d9370/eval.go#L1373

(this was the result of a user error, but I would imagine it would be good not to panic in this situation regardless)

**Comment by alandonovan** [comment]
As you point out, nil is not a valid skylark.Value, so passing nil to Call is a user error, that is, a bug in the Go program, not an expected error caused by evaluation of the Skylark function.  A panic is thus the correct way to report the mistake. (Returning an error would cause the bug to remain latent.)

I have no problem with adding an explicit precondition check such as `if fn == nil { panic("Call(fn=nil)") }` if it would cause a violation to be discovered sooner, or more clearly, than it otherwise would, but in this instance fn is dereferenced eagerly by `fn.Type()`, and the failure can be unambiguously attributed to the nil pointer as there is no other operation on that line that can fail.

So the program is working as intended.
