### ISSUE TITLE
Examples of parsing a BUILD file

### ISSUE THREAD

**Issue by achew22** [google/skylark#109]
Are there any examples of parsing BUILD files using the skylark parser? For https://github.com/bazelbuild/bazel-watcher it would be great if it were possible to parse the BUILD files without taking the Bazel lock so we could, in parallel, build and compute source files to watch. Do you know of any code that is doing this already?

**Comment by laurentlb** [comment]
Do you need to parse the `BUILD` file, or to evaluate it? What do you want to do with the AST exactly? If you need a list of dependencies, the best is to call `bazel query`.

**Comment by achew22** [comment]
@laurentlb, thanks for the comment!

> Do you need to parse the `BUILD` file, or to evaluate it?

I would like to understand the dependency graph of a target in order to determine the transitive closure of all source files required to build it.

> What do you want to do with the AST exactly? If you need a list of dependencies, the best is to call bazel query.

Right now iBazel does [this](https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/ibazel.go#L53) with bazel query. Unfortunately, the query consumes the lock for the Bazel server. In an ideal world it would be possible to invoke both the build of the server/test to run, and to parse the `BUILD` files at the same time, but that doesn't seem to be possible today with the locking in Bazel.

I'm trying to minimize the time from user types `ibazel test //path/to:target` to the target being executed. For me, the query will take several orders of magnitude more time than the test actually takes to run. Relatively small golang tests clock in at `<0.1s` while the `bazel query` to find dependencies can take `10-15s`. Can you help me come up with a strategy for decreasing this ratio? Even 1:1 would be a big improvement. Further it seems a bit of a kludge to be invoking `bazel query` from the command line. I've wondered for a while now if it would be possible to get a gRPC connection to the Bazel server to directly make the query. Maybe that would be a superior way of achieving this goal.

How do you think we could improve speed in iBazel?

**Comment by alandonovan** [comment]
On 18 June 2018 at 16:46, Andrew Z Allen <notifications@github.com> wrote:

> I would like to understand the dependency graph of a target in order to
> determine the transitive closure of all source files required to build it.
>
To get from the BUILD file to its dependencies is a lot more work than
merely running the Skylark parser. You would need to evaluate the file in
the correct environment, which defines the 'rule' function and a hundred
others, instantiate targets, then construct and traverse the dependency
graph; it can't be done in less than 10,000 additional lines of Go code.
The difference between that functionality and a complete rewrite of 'bazel
query' is really very small.


> What do you want to do with the AST exactly? If you need a list of
> dependencies, the best is to call bazel query.
>
> Right now iBazel does this
> <https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/ibazel.go#L53>
> with bazel query. Unfortunately, the query consumes the lock for the Bazel
> server. In an ideal world it would be possible to invoke both the build of
> the server/test to run, and to parse the BUILD files at the same time,
> but that doesn't seem to be possible today with the locking in Bazel.
>
> I'm trying to minimize the time from user types ibazel test
> //path/to:target to the target being executed. For me, the query will
> take several orders of magnitude more time than the test actually takes to
> run. Relatively small golang tests clock in at <0.1s while the bazel query
> to find dependencies can take 10-15s. Can you help me come up with a
> strategy for decreasing this ratio? Even 1:1 would be a big improvement.
> Further it seems a bit of a kludge to be invoking bazel query from the
> command line. I've wondered for a while now if it would be possible to get
> a gRPC connection to the Bazel server to directly make the query. Maybe
> that would be a superior way of achieving this goal.
>

Making RPCs to the Bazel server directly is not going to help: the
client/server protocol is an (unfortunate) implementation detail, and in
any case, the client does ~no work and the server does ~all the work, so to
get any benefit the server would have to support concurrent requests.


> How do you think we could improve speed in iBazel?
>
Believe me, I feel your pain. Ideally bazel query could be made a lot
faster; it would be quite feasible to implement all the pieces required for
bazel query so that they run about 10x faster, without even
using a persistent server, and thus no server lock, but doing so would be a
substantial project. For Google-internal tools, one approach we use is to
have query tools specify an alternative --output_base=/tmp/foo, and thus
they talk to a separate Bazel server instance distinct from the one used
for builds.  But I imagine this approach may be trickier for bazel than for
blaze because of the repository features which cause expensive side effects
during loading.

**Comment by achew22** [comment]
@alandonovan, thanks for your thoughts

It sounds to me like this is a hard problem (tm)... darn. Do you or @laurentlb have any ideas that could be implemented now in order to improve the performance?

**Comment by achew22** [comment]
Friendly ping

**Comment by laurentlb** [comment]
> the query consumes the lock for the Bazel server

There has been some work to remove the lock, but it's complicated. I don't know when it will be ready. I can't suggest a good workaround available now.

> small golang tests clock in at <0.1s while the bazel query to find dependencies can take 10-15s

`bazel query` should be faster than `bazel test` on the same target. Once the server is running, bazel should be much faster.
