### ISSUE TITLE
Expose API to rerun a skylark script with different globals?

### ISSUE THREAD

**Issue by natefinch** [google/skylark#4]
From looking at eval.go, it looks like the parsing of a script could be done once and then re-evaluated with different globals multiple times, saving the overhead of the parsing step.  Is that something you'd be interested in supporting?  I know skylark is used just for configuration in bazel, and thus is probably not rerun unless the script changes, but I would like to be able to use this for user-created logic in Go programs, such as adding custom functions to a template parser (like Hugo).  In those cases, the same skylark code would be run over and over with different globals.  It would be nice if this were supported in the skylark package itself.

**Comment by alandonovan** [comment]
That seems reasonable, but the challenge is to support this (and related) use cases without complicating the API.  At present the Exec function does (1) parsing, (2) resolving, (3) frame creation, (4) execution, (5) freezing.  Perhaps a good first step would be, rather than to add a new abstraction, to expose a way to do 3 and 4 and then clients can just copy/paste the Exec function and modify it to their needs.

**Comment by natefinch** [comment]
That sounds good to me.  Exec is pretty simple, I'm fine with having to copy that minimal logic.  This stands out as the only part that would be good to refactor into something usable externally:

```go
	fr := &Frame{
		thread:  thread,
		parent:  thread.frame,
		globals: globals,
		locals:  make([]Value, len(f.Locals)),
	}
	thread.frame = fr
	err = execStmts(fr, f.Stmts)
	thread.frame = fr.parent
```

The frame stuff seems a little twisty with assigning frames to threads and threads to frames, and execStmts turns into a big ugly switch that I would hate to have to recreate.

**Comment by alandonovan** [comment]
Fixed by https://github.com/google/skylark/commit/7b0e4c35f1db24805bfcf6e0c409f9acf561319d .

**Comment by natefinch** [comment]
awesome, thanks! :)
