### ISSUE TITLE
globals provided to exec can be overwritten by module

### ISSUE THREAD

**Issue by warpfork** [google/skylark#75]
In skylark, repeated assignments to global variables are supposed to be a compile time error.  E.g. `a="foo"; a="bar"` is an error -- `"cannot reassign global a declared at [...]"`.

However, if I define a global in my go code that is calling `skylark.Exec(...)`, and then assign to that in my skylark script, there's no error.  This seems inconsistent and surprising.

It seems like the globals I provide to Exec are treated roughly as if they're in the [universe block](https://github.com/google/skylark/blob/master/doc/spec.md#built-in-constants-and-functions) in that assignments can shadow them... but they're also *not* treated like the universe block because they'll still be in the globals StringDict after the Exec returns.

I'm not sure if this is a bug or just a documentation request. :)

(In case it's relevant, here's why I'm asking: I'd like to be providing some more builtin functions to use without load statements in my skylark scripts... and I don't want them to appear in the globals StringDict result of the module's evaluation.  Is putting my additional builtins into reach by putting them in the globals when I start Exec going about this the wrong way, and I should be using a different approach?  Thanks for any advice.)

**Comment by alandonovan** [comment]
The reason for the different handling of predefined and user-defined globals is that applications typically evolve to predefine more names, and it creates a major compatibility problem if each addition breaks some user programs.  The same rationale applies to re-definitions of names in the universe block.

(We could relax the redefinition check entirely, like Python does. You can already mutate global variables in a sequence of statements, so why treat rebinding specially?  The Bazel Skylark team asserts that this restriction makes programs easier to read.)

You are right that those globals will remain in the module StringDict after execution. Furthermore, it would not be safe for your application to detect that it put the extra names in there and remove them after module execution if they're unchanged, because any functions defined in the module refer to global variables by doing lookups in the module StringDict. This late binding is not strictly necessary, and could be eliminated (and made more efficient) by having the resolver number globals the same way it does locals, and having functions close over their global environment in addition to lexically enclosing locals. (I did this at some point but it didn't seem necessary.  I could revisit it, perhaps without even changing the API.)

So, yes, I should document this better; and I'll investigate flat closures for globals.

**Comment by warpfork** [comment]
I like the strict redefinition check!  I mostly wondered why it doesn't apply here.  For what it's worth, I'd be happier in my use case if the strict check did apply here (I was actually thinking about injecting some statements of `"a=a; b=b"` to the exec as a hack to make them unassignable).

Flattening out the late binding would be awesome.  I didn't realize there was late binding there until you mentioned in here, and I think that'll force me to review some of my design plans.

**Comment by alandonovan** [comment]
I spent some time investigating and found more questions than answers. Bazel doesn't consider predeclared non-universe names as part of the module: it effectively lumps the universe and the predeclared globals together as one category, "predeclared". Perhaps that's what the spec and Go impl should do too. The API is going to have to change.

[waiting for conclusion of Google internal issue b/74460309]

**Comment by alandonovan** [comment]
The API change is unfortunate, but this change should solve your problem.

**Comment by warpfork** [comment]
I just updated my submodules today and spent 0.05 seconds being startled something broke, and then seeing what the diff was and being thrilled.

I had forged ahead and built some hacks to get the behavior I wanted, and have now deleted them all and my regression tests still pass.  I'm delighted.

Thank you for this!

I notice that "Predeclared" variables can still be shadowed.  Assuming that's the intent, the docs request still stands, though I'm very happy with the new name of this field in ExecOptions.  Otherwise I'm happy to consider this issue closed if you are :)

**Comment by warpfork** [comment]
Oh, hang on.  I have a follow-up bug for you.  It seems if I do shadow one of my "predeclared" variables, that value will still not be in the returned globals dict -- this probably seems not the intent?

**Comment by alandonovan** [comment]
Sorry for the breakage, but there was no way to fix the problem without an API change. Glad the fix helped.  

>  It seems if I do shadow one of my "predeclared" variables, that value will still not be in the returned globals dict

That would certainly be a bug, but I can't reproduce it. Can you send me a test case?
