### ISSUE TITLE
Document how to exit repl

### ISSUE THREAD

**Issue by abergmeier** [google/skylark#85]
tldr; no obvious way to exit repl and ctrl+c does not work.

**Comment by alandonovan** [comment]
Use Ctrl-D to close stdin, like in the shell, gdb, Python, nslookup, etc.

**Comment by alandonovan** [comment]
Since this is a question of general UNIX knowledge and nothing specific to Skylark, I would prefer to follow those other tools and avoid cluttering the UI with "helpful" hints.  I have added a note to the README page, though.

**Comment by PaluMacil** [comment]
EDIT: oh, I'm also in the wrong repo... oops

@alandonovan I used Linux as my primary personal OS since 2008 and use MacOS for work as a software engineer, and I had never heard of ctrl-D before this issue here. I've closed Python's repl with `exit()` and shells with `exit`. I don't think assuming people will know a shortcut in an environment where some people are used to entering commands is a good assumption. I _should_ have spotted the instruction in the README, but after I tried the common things in the other environments I'm familiar using, I went straight to searching issues, assuming someone would have a feature request open.

I know this has been closed for years, so it is probably not very useful to comment here, but I also don't know that my feelings on this are very strong, so it's okay, but if others have strong opinions, I figured my experience, in light of my other unix system familiarity, might be good input.
